server:
  port: 8080
#  context-path: /sso
#  address: sso.server

spring:
  mvc:
    static-path-pattern: /**
    # д╛хож╣н╙ classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/